### ISSUE TITLE
remove patientID box from clinical data search 

### ISSUE THREAD

**Issue by kcranston** [CanDIG/candig-data-portal#65]
This patient ID box is not a search field, and serves no real purpose. We can get rid of it. 

<img width="393" alt="Screen Shot 2022-11-03 at 2 27 19 PM" src="https://user-images.githubusercontent.com/312034/199804639-e4101752-9b1a-4b5f-b181-ab5bac592933.png">

**Comment by CourtneyGosselin** [comment]
The patient ID box serves the purpose of which user is currently selected in the JSON table

**Comment by kcranston** [comment]
Ok, I see what it does now. I still think it is confusing up in the same row as the search boxes, so maybe we should re-think the location. Or whether we can convey the information about what patient is displayed in the json box in a clearer way.
