### ISSUE TITLE
search by cancer code / types is buggy or data formatting is wrong

### ISSUE THREAD

**Issue by kcranston** [CanDIG/candig-data-portal#67]
I have patients with the following cancer_conditions:

```
"cancer_condition": {
  "body_site":"Pancreas",
  "code": { "id":"C25.9", "label":string"Not available" }
}

"cancer_condition": {
  "body_site": {"id":"Placeholder", "label" : "Ovarian cancer"},
  "code":{ "id":"C56.9", "label":"Not available"}
}

```

A search for Cancer_type = Ovary C56.9 returns 0 rows (should return patient 2)
A search for Cancer_type = Pancreas C25.9 returns the first patient (correct!)
Body Site = Ovarian Cancer returns 0 rows (should return patient 2)
Body Site = Pancreas doesn't even show up in the list of options

**Comment by CourtneyGosselin** [comment]
The data-portal is expecting body-site to be a dictionary 
`     body_site: [
        {
            id: 'UNK:0002',
            label: 'Breast'
        }
],`
